# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../../../base/gke

components:
  - ../../../components/gke/resources/gpu/1-L4
  # - ../../../components/hpa/vllm/token-latency # HPA is a work-in-progress

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - options:
      allowNameChange: true
    path: hpa.patch.yaml
    target:
      kind: HorizontalPodAutoscaler
  - options:
      allowNameChange: true
    path: podmonitoring.patch.yaml
    target:
      kind: PodMonitoring
