apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app: gemma-2b-vllm-inference-server
  name: gemma-2b-vllm-podmonitoring
spec:
  selector:
    matchLabels:
      app: gemma-2b-vllm-inference-server
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
